name: Test and Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit
  build_apk:
    uses: ./.github/workflows/buildApk.yml
    needs: [tests]
    secrets: inherit