name: Build apk and upload to github

on:
  push:
    branches: [master]
  

jobs:
  build_apk:
    environment: release
    runs-on: ubuntu-latest
    env:
     Keystore: ${{ secrets.KEYSTORE }}
     Signing: ${{ secrets.SIGNING_PROPERTIES }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Move Signing Properties to project
        run: echo "$Signing" | base64 -d > ./android/signing.properties
      - name: Move keystore to project
        run: echo "$Keystore" | base64 -d > ./android/CaviKeystore.jks
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: 'stable'
      - name: Restore packages
        run: flutter pub get
        
      - name: Build apk
        run: flutter build apk --release
      
      - id: read_version
        run: |
          VERSION=`cat ./pubspec.yaml | grep -o 'version:[^:]*' | cut -f2 -d":" | xargs`
          echo "::set-output name=version::$(echo $VERSION)"
        shell: bash
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/app.apk
          asset_name: ZacatrusaApp.apk
          release_name: "Zacatrusa Android"
          tag: ${{ steps.read_version.outputs.version }}
          overwrite: true
          body: "Aplicación en Android de Zacatrusa"
      
