name: Test and Build

on:
  push:
    branches: [master, github_action]

jobs:
  tests:
    uses: ./.github/workflows/tests.yml@latest
    secrets: inherit
  build_apk:
    uses: ./.github/workflows/buildApk.yml@latest
    needs: [tests]
    secrets: inherit