name: Build apk and upload to github

on:
  push:
    branches: [master, github_action]
  

jobs:
  build_apk:
    permissions: write-all
    environment: release
    runs-on: ubuntu-latest
    env:
     Keystore: ${{ secrets.KEYSTORE }}
     Signing: ${{ secrets.SIGNING_PROPERTIES }}
     firebase_options: ${{ secrets.FIREBASE_OPTIONS }}
     algolia: ${{secrets.ALGOLIA_APPLICATION}}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3.5.3

      - name: Move Signing Properties to project
        run: echo "$Signing" | base64 -d > ./android/signing.properties

      - name: Move keystore to project
        run: echo "$Keystore" | base64 -d > ./android/CaviKeystore.jks

      - name: Move firebase options to project
        run: echo "$firebase_options" | base64 -d > ./lib/firebase_options.dart

      - name: Move algolia Application
        run: echo "$algolia" | base64 -d > ./lib/algolia_application.dart

      - run: sudo apt install tree
      - run: tree -d

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: 'stable'
      - name: Restore packages
        run: flutter pub get
        
      - name: Build apk
        run: flutter build apk --release
      
      - id: read_version
        run: |
          VERSION=`cat ./pubspec.yaml | grep -o 'version:[^:]*' | cut -f2 -d":" | xargs`
          echo "::set-output name=version::$(echo $VERSION)"
        shell: bash
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@2.6.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/app.apk
          asset_name: ZacatrusaApp.apk
          release_name: "Farma Compara Android"
          tag: ${{ steps.read_version.outputs.version }}
          overwrite: true
          body: "Comparador de Farmacias"
      
